INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (1001, CURRENT_DATE(), 'Vincenzo');
INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (1002, CURRENT_DATE(), 'Peppe');
INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (1003, CURRENT_DATE(), 'Giovanni');
