INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (10001, CURRENT_DATE(), 'Vincenzo');
INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (10002, CURRENT_DATE(), 'Peppe');
INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (10003, CURRENT_DATE(), 'Giovanni');
