INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (10001, CURRENT_DATE(), 'Vincenzo');
INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (10002, CURRENT_DATE(), 'Peppe');
INSERT INTO USER_DETAILS(ID, BIRTHDAY, NAME) VALUES (10003, CURRENT_DATE(), 'Giovanni');

INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20001, 'I want to learn AWS', 10001);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20002, 'I want to learn DevOps', 10001);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20003, 'I want to learn a kjf', 10002);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20004, 'I want to learn dsfa', 10002);